### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by NathanielTheWeeb** [Skylortrexler/apotheosis#2]
I play on a modded fabric multiplayer server with my friends, and nothing happens whenever we try to use the altars. Also, breaking the altar causes the server to crash.

**Comment by skylorbeck** [comment]
Hey thanks! I was unable to properly test multiplayer as I had no community of people willing to test. Can you send the crash log?

**Comment by NathanielTheWeeb** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/1/21, 9:34 AM
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_2189 cannot be cast to class website.skylorbeck.minecraft.exaltation.blocks.AltarAbstract (net.minecraft.class_2189 and website.skylorbeck.minecraft.exaltation.blocks.AltarAbstract are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @2e3967ea)
	at website.skylorbeck.minecraft.exaltation.blocks.screens.AltarScreenHandler.method_7597(AltarScreenHandler.java:110)
	at net.minecraft.class_3222.method_5773(class_3222.java:434)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at website.skylorbeck.minecraft.exaltation.blocks.screens.AltarScreenHandler.method_7597(AltarScreenHandler.java:110)
	at net.minecraft.class_3222.method_5773(class_3222.java:434)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 5999
	Entity Name: ScottishTurtle
	Entity's Exact location: 781.50, 64.00, -355.80
	Entity's Block location: World: (781,64,-356), Section: (at 13,0,12 in 48,4,-23; chunk contains blocks 768,0,-368 to 783,255,-353), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)

-- Affected level --
Details:
	All players: 1 total; [class_3222['ScottishTurtle'/5999, l='ServerLevel[world]', x=781.50, y=64.00, z=-355.80]]
	Chunk stats: 3860
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,65,-256), Section: (at 0,1,0 in 8,4,-16; chunk contains blocks 128,0,-256 to 143,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1400962 game time, 1130819 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 138935 (now: false), thunder time: 11290 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 3.10.0-1160.25.1.el7.x86_64
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 343772872 bytes (327 MiB) / 2210398208 bytes (2108 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3800X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 64394.65
	Virtual memory used (MB): 53917.39
	Swap memory total (MB): 32257.00
	Swap memory used (MB): 12011.00
	JVM Flags: 2 total; -Xms128M -Xmx4096M
	Fabric Mods: 
		acorigins: ArchesOrigins 0.3.2
		apoli: Apoli 1.0.4
		architectury: Architectury 2.5.28
		attributefix: Attribute Fix {FABRIC} 1.0.3
		beetleorigin: A Beetle Origin 2.0
		calio: Calio 1.0.2
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		cloudorigin: A Cloud Origin 1.0
		craborigin: A Crab Origin 1.0
		deerorigin: A Deer Origin 3.0
		demonorigin: A Demon Origin 3.0
		dual_riders: DualRiders 1.0.5
		exaltation: Exaltation 0.1.6
		extraorigins: Extra Origins 1.17-8
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.7
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		geckolib3: Geckolib 3.0.15
		genesis: Genesis 0.7
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libgui: LibGui 4.0.0-beta.4+1.17-rc1
		libninepatch: LibNinePatch 1.1.0
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		pehkui: Pehkui 2.4.0+1.14.4-1.17.1
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		skylorlib: SkyLib 1.0.4
		slimeorigin: Slimeorigin 4.0.0
	Player Count: 1 / 20; [class_3222['ScottishTurtle'/5999, l='ServerLevel[world]', x=781.50, y=64.00, z=-355.80]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by NathanielTheWeeb** [comment]
I tested it in a single-player world, and it worked fine, so I don't think it's having a problem with any other mods.

**Comment by skylorbeck** [comment]
I found the issue. I attempted to look for server side only data on a client side only class. I'm refactoring today and hopefully it'll be fixed soon. Thank you for the report!

**Comment by NathanielTheWeeb** [comment]
Thanks!

**Comment by skylorbeck** [comment]
Update released. Please update skylib as well.

**Comment by skylorbeck** [comment]
Just realized I never tested the server crash on break

**Comment by skylorbeck** [comment]
Cannot replicate server crash on break
