### ISSUE TITLE
"Orb of Origin" not reseting player class experience

### ISSUE THREAD

**Issue by Bladesunder** [Skylortrexler/apotheosis#5]
The Orb of Origin is an item that is currently only obtainable through commands or the creative menu. It is used by the Origins mod to give players an easy way to change their origin. When the orb of origin is used while the player is holding a leveled class, despite being able to change their profession, the amount of class experience remains at its previous level

**Comment by Bladesunder** [comment]
BTW sick mod! Really liked how in-depth it was despite it still being in the beta!

**Comment by skylorbeck** [comment]
Thanks for the report! Please use the commands to change classes, for now but I will look into adding functionality to the orb.

**Comment by Bladesunder** [comment]
Will do! Thanks for the quick response!
