### ISSUE TITLE
DoT Manasmith Skill not working

### ISSUE THREAD

**Issue by Bladesunder** [Skylortrexler/apotheosis#6]
When I select Manasmith as my profession and choose the DoT skill, despite hitting mobs with a sword, there seems to be no effect applied to the mob...

Also a question, I noticed that in the design documents that some of the classes don't match up with what is currently enacted within the mod (for example no blast arrow option within the archer class). I am wondering if you are still implementing the current classes or if the classes that are out now will be the final product.

**Comment by skylorbeck** [comment]
It's been a while but I believe the skill is all crafted swords gain DoT. The class is centered around crafting, after all.

Yes, the classes are different from the design docs. This is a natural part of game (and mod) development. Not every feature is as easy as envisioned, and time constraints exist.

**Comment by Bladesunder** [comment]
1. My apologies, I should have clarified that I did use a sword that I crafted after unlocking the DoT crafting skill.

2. So does this mean that the classes that are currently published are completed?

**Comment by skylorbeck** [comment]
Would you upload some screenshots of the sword you crafted so I can see what enchants are on it? The DoT effect is achieved by enchanting the sword. 

"Completed" in the sense that they will only really be receiving balance tweaks and bugfixes, yes.

**Comment by Bladesunder** [comment]
<img width="193" alt="Screen Shot 2021-11-04 at 5 13 30 PM" src="https://user-images.githubusercontent.com/93627834/140438114-918fa158-f430-4ef2-8610-ae0865741715.png">

Thanks for you help!

**Comment by skylorbeck** [comment]
Huh yeah that definitely should have an enchantment. Can you send me a screenshot of the Class page as well? I wonder if the branch of classes you picked didn't have the proper power assigned.

**Comment by Bladesunder** [comment]
<img width="521" alt="Screen Shot 2021-11-04 at 6 06 26 PM" src="https://user-images.githubusercontent.com/93627834/140441316-081f8273-200d-4b92-b037-031d7492e479.png">

**Comment by skylorbeck** [comment]
I mean the whole decision tree to where you are at. Each branch is a different class and in testing sometimes certain combos wouldn't get updated properly and were missing some powers. It's possible the branch you took is missing the power, but has the description.

**Comment by Bladesunder** [comment]
I attempted both upgrade paths and I still am unable to do DoT...
Maybe there is a placeholder enchant instead of the custom DoT one? I noticed that the extra sharpness enchant appears whenever I select the DoT skill...
