### ISSUE TITLE
Issues with Blacksmith Class

### ISSUE THREAD

**Issue by Bladesunder** [Skylortrexler/apotheosis#7]
1. Speedbooster enchantment shows raw name
2. Enchantments over 10 start showing their raw value (Not sure there is an easy way to fix this as this is a vanilla issue as well)
3. Crafted chestplates do not have fitness enchantment even after selecting the skill that gives higher DMG per armor piece
4. Not an issue but is the randomized enchantments for Manasmith intentional? I assume it is..
1) <img width="361" alt="Screen Shot 2021-11-04 at 8 31 07 PM" src="https://user-images.githubusercontent.com/93627834/140455107-0cb14d0d-6235-49aa-afa5-d21b0fd6fa9a.png">
2) <img width="255" alt="Screen Shot 2021-11-04 at 8 36 47 PM" src="https://user-images.githubusercontent.com/93627834/140455134-7885fea8-5851-4377-afe5-4c1f779a41d5.png">
3) <img width="252" alt="Screen Shot 2021-11-04 at 8 48 16 PM" src="https://user-images.githubusercontent.com/93627834/140455295-8311e6ab-fdd7-41d5-932d-bfe5978751fc.png">

**Comment by skylorbeck** [comment]
2. Vanilla issue, some other mods fix this
4. Yes, read the first power Magesmith gets.

**Comment by skylorbeck** [comment]
Thanks for the report!
